[2025-05-18T22:45:12.272+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:45:12.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:45:12.315+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:45:12.308+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:45:12.502+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:45:12.480+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:45:12.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:45:13.082+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.887 seconds
[2025-05-18T22:45:43.528+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:45:43.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:45:43.532+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:45:43.532+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:45:43.546+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:45:43.545+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:45:43.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:45:43.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.078 seconds
[2025-05-18T22:46:14.003+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:46:14.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:46:14.009+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:46:14.008+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:46:14.026+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:46:14.024+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:46:14.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:46:14.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.148 seconds
[2025-05-18T22:46:44.426+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:46:44.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:46:44.442+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:46:44.439+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:46:44.462+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:46:44.459+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:46:44.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:46:44.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.097 seconds
[2025-05-18T22:47:15.077+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:47:15.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:47:15.089+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:47:15.088+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:47:15.109+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:47:15.105+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:47:15.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:47:15.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.104 seconds
[2025-05-18T22:47:45.569+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:47:45.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:47:45.582+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:47:45.579+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:47:45.621+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:47:45.619+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:47:45.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:47:45.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.102 seconds
[2025-05-18T22:48:16.332+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:48:16.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:48:16.339+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:48:16.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:48:16.361+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:48:16.359+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:48:16.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:48:16.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.116 seconds
[2025-05-18T22:48:46.989+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:48:46.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:48:46.999+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:48:46.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:48:47.025+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:48:47.022+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:48:47.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:48:47.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.098 seconds
[2025-05-18T22:49:17.500+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:49:17.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:49:17.522+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:49:17.521+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:49:17.542+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:49:17.539+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:49:17.542+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:49:17.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.225 seconds
[2025-05-18T22:49:48.150+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:49:48.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:49:48.160+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:49:48.158+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:49:48.181+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:49:48.179+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:49:48.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:49:48.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.078 seconds
[2025-05-18T22:50:18.800+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:50:18.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:50:18.807+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:50:18.806+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:50:18.828+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:50:18.826+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:50:18.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:50:18.980+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.192 seconds
[2025-05-18T22:50:49.338+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:50:49.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:50:49.345+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:50:49.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:50:49.362+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:50:49.360+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:50:49.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:50:49.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.093 seconds
[2025-05-18T22:51:19.839+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:51:19.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:51:19.856+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:51:19.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:51:19.873+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:51:19.871+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:51:19.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:51:19.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.087 seconds
[2025-05-18T22:51:50.265+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:51:50.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:51:50.271+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:51:50.270+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:51:50.291+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:51:50.288+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:51:50.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:51:50.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.080 seconds
[2025-05-18T22:52:21.137+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:52:21.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:52:21.146+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:52:21.145+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:52:21.163+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:52:21.161+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:52:21.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:52:21.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.093 seconds
[2025-05-18T22:52:52.055+0000] {processor.py:161} INFO - Started process (PID=239) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:52:52.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:52:52.062+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:52:52.061+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:52:52.078+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:52:52.076+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:52:52.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:52:52.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.101 seconds
[2025-05-18T22:53:22.754+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:53:22.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:53:22.770+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:53:22.767+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:53:22.795+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:53:22.793+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:53:22.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:53:22.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.098 seconds
[2025-05-18T22:53:53.127+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:53:53.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:53:53.133+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:53:53.132+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:53:53.148+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:53:53.147+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:53:53.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:53:53.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.073 seconds
[2025-05-18T22:54:23.521+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:54:23.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:54:23.526+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:54:23.526+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:54:23.555+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:54:23.551+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:54:23.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:54:23.647+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.136 seconds
[2025-05-18T22:54:54.083+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:54:54.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:54:54.093+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:54:54.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:54:54.109+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:54:54.107+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:54:54.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:54:54.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.104 seconds
[2025-05-18T22:55:24.678+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:55:24.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:55:24.685+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:55:24.684+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:55:24.706+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:55:24.704+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:55:24.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:55:24.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.095 seconds
[2025-05-18T22:55:55.172+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:55:55.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:55:55.185+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:55:55.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:55:55.267+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:55:55.259+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:55:55.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:55:55.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.201 seconds
[2025-05-18T22:56:25.632+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:56:25.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:56:25.637+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:56:25.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:56:25.662+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:56:25.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:56:25.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:56:25.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.108 seconds
[2025-05-18T22:56:56.122+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:56:56.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:56:56.134+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:56:56.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:56:56.172+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:56:56.169+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:56:56.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:56:56.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.102 seconds
[2025-05-18T22:57:26.638+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:57:26.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:57:26.648+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:57:26.647+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:57:26.692+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:57:26.689+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:57:26.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:57:26.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.123 seconds
[2025-05-18T22:57:57.070+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:57:57.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:57:57.077+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:57:57.076+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:57:57.096+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:57:57.093+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:57:57.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:57:57.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.127 seconds
[2025-05-18T22:58:27.619+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:58:27.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:58:27.627+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:58:27.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:58:27.645+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:58:27.643+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:58:27.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:58:27.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.081 seconds
[2025-05-18T22:58:57.993+0000] {processor.py:161} INFO - Started process (PID=299) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:58:57.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:58:57.999+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:58:57.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:58:58.018+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:58:58.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:58:58.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:58:58.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.069 seconds
[2025-05-18T22:59:28.502+0000] {processor.py:161} INFO - Started process (PID=304) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:59:28.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:59:28.512+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:59:28.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:59:28.530+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:59:28.528+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:59:28.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:59:28.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.101 seconds
[2025-05-18T22:59:58.869+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T22:59:58.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T22:59:58.879+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:59:58.878+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:59:58.896+0000] {logging_mixin.py:188} INFO - [2025-05-18T22:59:58.894+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T22:59:58.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T22:59:58.953+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.094 seconds
[2025-05-18T23:00:29.225+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:00:29.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:00:29.232+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:00:29.231+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:00:29.258+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:00:29.254+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:00:29.258+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:00:29.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.116 seconds
[2025-05-18T23:00:59.671+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:00:59.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:00:59.678+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:00:59.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:00:59.701+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:00:59.697+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:00:59.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:00:59.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.102 seconds
[2025-05-18T23:01:30.061+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:01:30.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:01:30.070+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:01:30.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:01:30.089+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:01:30.087+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:01:30.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:01:30.122+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.094 seconds
[2025-05-18T23:01:46.341+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:01:46.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:01:46.354+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:01:46.348+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:01:46.378+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:01:46.376+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:01:46.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:01:46.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.088 seconds
[2025-05-18T23:02:17.109+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:02:17.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:02:17.117+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:02:17.116+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:02:17.134+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:02:17.132+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:02:17.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:02:17.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.112 seconds
[2025-05-18T23:02:47.542+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:02:47.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:02:47.553+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:02:47.552+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:02:47.594+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:02:47.590+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:02:47.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:02:47.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.177 seconds
[2025-05-18T23:03:18.100+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:03:18.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:03:18.110+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:03:18.109+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:03:18.148+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:03:18.137+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:03:18.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:03:18.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.131 seconds
[2025-05-18T23:03:48.652+0000] {processor.py:161} INFO - Started process (PID=349) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:03:48.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:03:48.661+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:03:48.660+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:03:48.678+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:03:48.677+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src import run_pipeline, train_model, save_model, load_model
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:03:48.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:03:48.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.072 seconds
[2025-05-18T23:04:11.008+0000] {processor.py:161} INFO - Started process (PID=354) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:04:11.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:04:11.013+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:04:11.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:04:11.021+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:04:11.019+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 19
    preds = 
            ^
SyntaxError: invalid syntax
[2025-05-18T23:04:11.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:04:11.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.066 seconds
[2025-05-18T23:04:17.152+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:04:17.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:04:17.172+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:04:17.170+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:04:17.184+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:04:17.182+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 19
    preds = 
            ^
SyntaxError: invalid syntax
[2025-05-18T23:04:17.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:04:17.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.095 seconds
[2025-05-18T23:04:34.416+0000] {processor.py:161} INFO - Started process (PID=364) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:04:34.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:04:34.446+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:04:34.442+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:04:34.472+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:04:34.470+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:04:34.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:04:34.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.099 seconds
[2025-05-18T23:05:04.982+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:05:04.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:05:04.993+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:05:04.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:05:05.013+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:05:05.010+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:05:05.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:05:05.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.113 seconds
[2025-05-18T23:05:35.562+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:05:35.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:05:35.569+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:05:35.568+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:05:35.589+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:05:35.587+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:05:35.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:05:35.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.087 seconds
[2025-05-18T23:05:57.320+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:05:57.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:05:57.327+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:05:57.326+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:05:57.352+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:05:57.350+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:05:57.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:05:57.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.143 seconds
[2025-05-18T23:06:27.973+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:06:27.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:06:27.993+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:06:27.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:06:28.013+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:06:28.011+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:06:28.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:06:28.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.120 seconds
[2025-05-18T23:06:58.323+0000] {processor.py:161} INFO - Started process (PID=389) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:06:58.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:06:58.329+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:06:58.328+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:06:58.373+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:06:58.371+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:06:58.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:06:58.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.102 seconds
[2025-05-18T23:07:28.821+0000] {processor.py:161} INFO - Started process (PID=394) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:07:28.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:07:28.827+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:07:28.826+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:07:28.872+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:07:28.866+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:07:28.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:07:28.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.177 seconds
[2025-05-18T23:07:59.510+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:07:59.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:07:59.515+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:07:59.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:07:59.547+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:07:59.545+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:07:59.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:07:59.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.093 seconds
[2025-05-18T23:08:30.073+0000] {processor.py:161} INFO - Started process (PID=404) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:08:30.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:08:30.080+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:08:30.079+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:08:30.096+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:08:30.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:08:30.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:08:30.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.066 seconds
[2025-05-18T23:09:00.468+0000] {processor.py:161} INFO - Started process (PID=409) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:09:00.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:09:00.474+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:09:00.474+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:09:00.489+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:09:00.488+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:09:00.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:09:00.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.108 seconds
[2025-05-18T23:09:31.307+0000] {processor.py:161} INFO - Started process (PID=414) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:09:31.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:09:31.313+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:09:31.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:09:31.343+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:09:31.341+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:09:31.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:09:31.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.094 seconds
[2025-05-18T23:10:02.396+0000] {processor.py:161} INFO - Started process (PID=419) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:10:02.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:10:02.412+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:10:02.411+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:10:02.448+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:10:02.445+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:10:02.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:10:02.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.149 seconds
[2025-05-18T23:10:32.995+0000] {processor.py:161} INFO - Started process (PID=424) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:10:32.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:10:33.002+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:10:33.001+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:10:33.022+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:10:33.020+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:10:33.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:10:33.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.086 seconds
[2025-05-18T23:11:03.388+0000] {processor.py:161} INFO - Started process (PID=429) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:11:03.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:11:03.394+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:11:03.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:11:03.408+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:11:03.406+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:11:03.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:11:03.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.089 seconds
[2025-05-18T23:11:33.775+0000] {processor.py:161} INFO - Started process (PID=434) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:11:33.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:11:33.782+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:11:33.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:11:33.797+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:11:33.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:11:33.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:11:33.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.078 seconds
[2025-05-18T23:12:04.174+0000] {processor.py:161} INFO - Started process (PID=439) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:12:04.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:12:04.180+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:12:04.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:12:04.219+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:12:04.217+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:12:04.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:12:04.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.091 seconds
[2025-05-18T23:12:34.649+0000] {processor.py:161} INFO - Started process (PID=444) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:12:34.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:12:34.656+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:12:34.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:12:34.689+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:12:34.687+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:12:34.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:12:34.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.084 seconds
[2025-05-18T23:13:05.088+0000] {processor.py:161} INFO - Started process (PID=449) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:13:05.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:13:05.093+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:13:05.093+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:13:05.136+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:13:05.134+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:13:05.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:13:05.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.098 seconds
[2025-05-18T23:13:35.505+0000] {processor.py:161} INFO - Started process (PID=454) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:13:35.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:13:35.511+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:13:35.510+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:13:35.550+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:13:35.548+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:13:35.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:13:35.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.098 seconds
[2025-05-18T23:14:05.921+0000] {processor.py:161} INFO - Started process (PID=459) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:14:05.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:14:05.926+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:14:05.925+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:14:05.942+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:14:05.940+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:14:05.942+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:14:05.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.061 seconds
[2025-05-18T23:14:36.302+0000] {processor.py:161} INFO - Started process (PID=464) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:14:36.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:14:36.307+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:14:36.307+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:14:36.324+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:14:36.322+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:14:36.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:14:36.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.066 seconds
[2025-05-18T23:15:06.688+0000] {processor.py:161} INFO - Started process (PID=469) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:15:06.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:15:06.700+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:15:06.697+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:15:06.723+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:15:06.722+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:15:06.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:15:06.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.086 seconds
[2025-05-18T23:15:37.274+0000] {processor.py:161} INFO - Started process (PID=474) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:15:37.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:15:37.280+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:15:37.280+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:15:37.296+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:15:37.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:15:37.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:15:37.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.068 seconds
[2025-05-18T23:16:07.719+0000] {processor.py:161} INFO - Started process (PID=479) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:16:07.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:16:07.724+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:16:07.723+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:16:07.740+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:16:07.738+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:16:07.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:16:07.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.062 seconds
[2025-05-18T23:16:38.523+0000] {processor.py:161} INFO - Started process (PID=484) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:16:38.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:16:38.529+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:16:38.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:16:38.545+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:16:38.543+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:16:38.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:16:38.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.066 seconds
[2025-05-18T23:17:08.879+0000] {processor.py:161} INFO - Started process (PID=489) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:17:08.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:17:08.885+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:17:08.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:17:08.902+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:17:08.900+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:17:08.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:17:08.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.078 seconds
[2025-05-18T23:17:39.302+0000] {processor.py:161} INFO - Started process (PID=494) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:17:39.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:17:39.308+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:17:39.307+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:17:39.338+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:17:39.335+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:17:39.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:17:39.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.088 seconds
[2025-05-18T23:18:09.706+0000] {processor.py:161} INFO - Started process (PID=499) to work on /opt/airflow/dags/nog_dag.py
[2025-05-18T23:18:09.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nog_dag.py for tasks to queue
[2025-05-18T23:18:09.711+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:18:09.710+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:18:09.728+0000] {logging_mixin.py:188} INFO - [2025-05-18T23:18:09.726+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/nog_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nog_dag.py", line 4, in <module>
    from src.data.data_pipeline import run_data_pipeline
ModuleNotFoundError: No module named 'src'
[2025-05-18T23:18:09.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nog_dag.py
[2025-05-18T23:18:09.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nog_dag.py took 0.063 seconds
